version: "3.7"

services:
  app:
    image: hello-spring
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: secret
      DB_NAME: hello
    ports:
      - 8081:8080
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: hello
